<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml-transitional.dtd">
<html>
<head>
    <title>全网合一管理后台</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="css/style.css"/>
    <script type="text/javascript" src="js/common.js"></script>
    <script type="text/javascript" src="js/jquery.js"></script>
</head>
<body>
{include file="head.phtml"}
<div class="main clearfix">
    {if $act eq 'list'}
    {include file="menu.phtml"}

    {/if}

    {if $act eq 'add'}
    {include file="menu.phtml"}
    <div class="content">
        <form name="addKfForm" method="post" >
            客服帐号：<input type="text" name="kf_account" value="" />@{$wechatAccount}<br />
            昵称：<input type="text" name="kf_nick" value="" /><br />
            密码：<input type="password" name="password" value="" /><br />
            <input type="submit" name="提交" value="提交" />
            <input type="hidden" name="opera" value="add" />
        </form>
    </div>
    {/if}

</div>
{include file="foot.phtml"}
</body>
</html>