<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<div class="menu">
<dl class="menu-list">
    <dt class="menu-title">系统模块</dt>
    <dd class="menu-item"><a href="main.php">起始页</a></dd>
</dl>

<dl class="menu-list">
    <dt class="menu-title">CMS模块</dt>
    <dd class="menu-item"><a href="article.php?act=add">新增文章</a></dd>
    <dd class="menu-item"><a href="articleCat.php">文章分类</a></dd>
    <dd class="menu-item"><a href="article.php">文章列表</a></dd>
</dl>

<dl class="menu-list">
    <dt class="menu-title">自定义菜单</dt>
    <dd class="menu-item"><a href="menu.php">菜单列表</a></dd>
</dl>

<dl class="menu-list">
    <dt class="menu-title">自动回复</dt>
    <dd class="menu-item"><a href="rule.php">回复规则</a></dd>
    <dd class="menu-item"> <a href="rule.php?act=add">添加回复规则</a></dd>
    <dd class="menu-item"><a href="response.php?act=add">新增回复</a></dd>
    <dd class="menu-item"><a href="response.php">自动回复列表</a></dd>
</dl>
<dl class="menu-list">
    <dt class="menu-title">用户管理</dt>
    <dd class="menu-item"><a href="user.php">用户列表</a></dd>
    <dd class="menu-item"><a href="userGroup.php">用户分组列表</a></dd>
    <dd class="menu-item"><a href="userGroup.php?act=add">添加用户分组</a></dd>
</dl>
<dl class="menu-list">
    <dt class="menu-title">客服</dt>
    <dd class="menu-item"><a href="custService.php">客服列表</a></dd>
    <dd class="menu-item"><a href="custService.php?act=add">添加客服帐号</a></dd>
</dl>
<dl class="menu-list">
    <dt class="menu-title">返回</dt>
    <dd class="menu-item"><a href="../../index.php">站点首页</a></dd>
    <dd class="menu-item"><a href="../../manager/main.php">cms后台</a></dd>
</dl>
</div>
