<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml-transitional.dtd">
<html>
<head>
    <title>全网合一管理后台</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="css/style.css"/>
    <script type="text/javascript" src="js/common.js"></script>
    <script type="text/javascript" src="js/jquery.js"></script>
</head>
<body>
{include file="head.phtml"}
<div class="main clearfix">
{if $act eq 'list'}
    {include file="menu.phtml"}
    <a href="userGroup.php?act=sync">同步</a>
    {if count($groups) eq 0}
    <p>没有分组</p>
    {else}
    <table>
        <thead>
        <th>id</th>
        <th>分组名</th>
        <th>创建时间</th>
        <th>粉丝数量</th>
        <th>操作</th>
        </thead>
        <tbody>
        {foreach $groups as $group}
        <tr>
            <td>{$group.id}</td>
            <td>{$group.name}</td>
            <td>{$group.addTime}</td>
            <td>{$group.count}</td>
            <td>
                <a href="userGroup.php?act=edit&id={$group.id}">编辑</a>
                <a href="userGroup.php?act=delete&id={$group.wechatId}">删除</a>
            </td>

        </tr>
        {/foreach}
        </tbody>
    </table>
    {/if}
{/if}
{if $act eq 'add'}
    {include file="menu.phtml"}
    <div class="content">
        <form name="userGroupAddForm" method="post">
            分组名：<input type="text" name="name" /><br />
            <input type="submit" name="submit" value="提交" />
            <input type="hidden" name="opera" value="add" />
        </form>
    </div>
{/if}
{if $act eq 'edit'}
{include file="menu.phtml"}
<div class="content">
    <form name="userGroupEidtForm" method="post">
        分组名：<input type="text" name="name" value="{$group.name}"/><br />
        <input type="submit" name="submit" value="提交" />
        <input type="hidden" name="opera" value="edit" />
        <input type="hidden" name="id" value="{$group.id}" />
    </form>
</div>
{/if}
{if $act eq 'sync'}
    {include file="menu.phtml"}
    <div class="content">
        <table>
            <thead>
            <th>id</th>
            <th>分组名</th>
            <th>粉丝数量</th>
            <th>操作</th>
            </thead>
            <tbody>
            {foreach $groups as $group}
            <tr>
                <td>{$group.wechatId}</td>
                <td>{$group.name}</td>
                <td>{$group.count}</td>
                <td>
                    <a href="userGroup.php?act=delete&id={$group.wechatId}">删除</a>
                </td>

            </tr>
            {/foreach}
            </tbody>
        </table>
    </div>
{/if}
</div>
{include file="foot.phtml"}
</body>
</html>