{include file="library/sidebar.lbi"}
<div class="contentpanel">
{if $act eq 'list'}
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-btns">
                <a class="minimize" href="">−</a>
            </div>
            <!--            <h4 class="panel-title">添加导航条</h4>-->
            <a class="btn btn-primary" href="adminUser.php?act=add">新增管理员</a>
        </div>
        <div class="panel-body panel-body-nopadding">
            <table class="table mb30" style="width: 98%; margin: 0 auto">
                <thead>
                <tr>
                    <th>#</th>
                    <th>帐号</th>
                    <th>姓名</th>
                    <th>邮件</th>
                    <th>手机</th>
                    <th>角色</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {foreach from=$admins item=admin name=admins}
                <tr>
                    <td>{$smarty.foreach.admins.iteration}</td>
                    <td>{$admin.account}</td>
                    <td>{$admin.name}</td>
                    <td>{$admin.email}</td>
                    <td>{$admin.mobile}</td>
                    <td>{$admin.roleName}</td>
                    <td>
                        {if $admin.roleId neq 1}
                        <a href="adminUser.php?act=edit&account={$admin.account}" title="编辑"><i class="fa fa-pencil"></i></a>&nbsp;|
                        <a class="delete-row" href="adminUser.php?act=delete&account={$admin.account}" title="删除"><i class="fa fa-trash-o"></i></a>
                        {/if}
                    </td>
                </tr>
                {/foreach}
                </tbody>
            </table>

        </div><!-- panel-body -->

        <div class="panel-footer">
        </div><!-- panel-footer -->

    </div>
{/if}

{if $act eq 'add'}
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-btns">
                <a class="minimize" href="">−</a>
            </div>
            <h4 class="panel-title">添加-管理员</h4>
        </div>
        <div class="panel-body panel-body-nopadding">
            <form name="adminAddForm" method="POST"  enctype="multipart/form-data" class="form-horizontal form-bordered">
                <div class="form-group">
                    <label class="col-sm-3 control-label">帐号</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" placeholder="" name="account">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">密码</label>
                    <div class="col-sm-4">
                        <input type="password" class="form-control" placeholder="" name="password">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">姓名</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" placeholder="" name="name">
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-3">性别</label>
                    <div class="col-sm-6">
                        <div class="radio"><label><input type="radio" name="sex" value="M" /> 男</label></div>
                        <div class="radio"><label><input type="radio"  name="sex" value="F" /> 女</label></div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">角色</label>
                    <div class="col-sm-2">
                        <select class="form-control " name="roleId">
                            {foreach from=$roles item=role}
                                <option value="{$role.id}">{$role.name}</option>
                            {/foreach}
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">邮箱</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" placeholder="" name="email">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">手机号码</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" placeholder="" name="mobile">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">头像</label>
                    <div class="col-sm-4">
                        <input type="file" class="form-control" placeholder="" name="photo" value="">
                    </div>
                </div>
                <div class="col-sm-6 col-sm-offset-3">
                    <button type="submit" class="btn btn-primary">添加</button>&nbsp;
                </div>
                <input type="hidden" name="opera" value="add"/>
            </form>
        </div>
        <div class="panel-footer">
        </div><!-- panel-footer -->
    </div>
{/if}

{if $act eq 'edit'}
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-btns">
                <a class="minimize" href="">−</a>
            </div>

            <h4 class="panel-title">编辑-{$admin.account}</h4>
        </div>
        <div class="panel-body panel-body-nopadding">
            <form name="adminEditForm" method="POST" class="form-horizontal form-bordered">
                <div class="form-group">
                    <label class="col-sm-3 control-label">修改密码</label>
                    <div class="col-sm-4">
                        <input type="password" class="form-control" placeholder="" name="password">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">姓名</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" placeholder="" name="name" value="{$admin.name}">
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-3">性别</label>
                    <div class="col-sm-6">
                        <div class="radio"><label><input type="radio" name="sex" value="M" {if $admin.sex eq 'M'}checked="checked"{/if}/> 男</label></div>
                        <div class="radio"><label><input type="radio"  name="sex" value="F" {if $admin.sex eq 'F'}checked="checked"{/if}/> 女</label></div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">角色</label>
                    <div class="col-sm-2">
                        <select class="form-control " name="roleId">
                            {foreach from=$roles item=role}
                            <option value="{$role.id}" {if $role.id eq $admin.roleId}selected="selected"{/if}>{$role.name}</option>
                            {/foreach}
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">邮箱</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" placeholder="" name="email" value="{$admin.email}">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">手机号码</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" placeholder="" name="mobile" value="{$admin.mobile}">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">头像</label>
                    <div class="col-sm-4">
                        <input type="file" class="form-control" placeholder="" name="photo" value="">
                    </div>
                    <div class="col-sm-4">
                        {if $admin.photo neq ''}
                        <img src="../{$admin.photo}"/>
                        {/if}
                    </div>
                </div>
                <div class="col-sm-6 col-sm-offset-3">
                    <button type="submit" class="btn btn-primary">更新</button>&nbsp;
                </div>
                <input type="hidden" name="opera" value="edit"/>
                <input type="hidden" name="account" value="{$admin.account}"/>
            </form>
        </div>
        <div class="panel-footer">
        </div><!-- panel-footer -->
    </div>
<!--<form name="adminEditForm" method="POST">-->
<!--<input type="hidden" name="account" value="{$admin.account}"/><br/>-->
<!--修改密码：<input type="password" name="password"/><br/>-->
<!--姓名：<input type="text" name="name" value="{$admin.name}"/><br/>-->
<!--性别：<input type="radio" name="sex" value="M" {if $admin.sex eq 'M'}checked="checked"{/if}/>男-->
<!--      <input type="radio" name="sex" value="F" {if $admin.sex eq 'F'}checked="checked"{/if}/>女<br/>-->
<!--角色：<select name="roleId">-->
<!--        {foreach from=$roles item=role}-->
<!--        <option value="{$role.id}" {if $role.id eq $admin.roleId}selected="selected"{/if}>{$role.name}</option>-->
<!--        {/foreach}-->
<!--     </select><br/>-->
<!--电子邮箱：<input type="text" name="email" value="{$admin.email}"/><br/>-->
<!--手机号码：<input type="text" name="mobile" value="{$admin.mobile}"/><br/>-->
<!--头像：<input type="file" name="photo"/><br/>-->
<!--{if $admin.photo neq ''}-->
<!--<img src="../{$admin.photo}"/>-->
<!--{/if}-->
<!--<input type="submit" name="submit" value="修改管理员"/>-->
<!--<input type="hidden" name="opera" value="edit"/>-->
<!--<input type="hidden" name="account" value="{$admin.account}"/>-->
<!--</form>-->

{/if}
</div><!-- contentpanel -->
{include file="library/footer.lbi"}
</body>
</html>