{include file="library/sidebar.lbi"}
<div class="contentpanel">
{if $act eq 'list'}
<a href="adminRole.php?act=add">添加管理员角色</a>
<table>
{foreach from=$adminRoles item=role}
<tr><td>{$role.name}</td>
    <td>
        <a href="adminRole.php?act=edit&id={$role.id}">编辑</a>|
        <a href="adminRole.php?act=delete&id={$role.id}">删除</a>
    </td>
</tr>
{/foreach}
</table>
{/if}

{if $act eq 'add'}
<form name="adminRoleAddForm" method="POST">
角色名：<input type="text" name="name" /><br/>
权限：<br />
{foreach from=$purview item=sub_purview key=name}
<input type="checkbox" name="purviews[{$name}]" value="{$name}" class="purview"/><br />
    {foreach from=$sub_purview item=pur}
<input type="checkbox" name="purviews[{$name}][]" value="{$pur}" class="sub-purview"/>{$purviewL.$pur}&nbsp;&nbsp;
    {/foreach}
<br />
{/foreach}
<br/>
<input type="submit" name="submit" value="添加角色"/>
<input type="hidden" name="opera" value="add"/>
</form>
<script type="text/javascript" src="js/adminRole.js"></script>
{/if}

{if $act eq 'edit'}
<form name="adminRoleEditForm" method="POST">
角色名：<input type="text" name="name" value="{$adminRole.name}"/><br/>
权限：<br />
{foreach from=$sub_purviewC item=sub_purview key=name}
    {if $purviewC.$name eq true}
        <input type="checkbox" name="purviews[{$name}]" value="{$name}" class="purview" checked="checked"/><br />
    {else}
        <input type="checkbox" name="purviews[{$name}]" value="{$name}" class="purview"/><br />
    {/if}
    {foreach from=$sub_purview item=check key=pur}
        {if $check eq true}
            <input type="checkbox" name="purviews[{$name}][]" value="{$pur}" class="sub-purview" checked="checked"/>{$purviewL.$pur}&nbsp;&nbsp;
        {else}
            <input type="checkbox" name="purviews[{$name}][]" value="{$pur}" class="sub-purview"/>{$purviewL.$pur}&nbsp;&nbsp;
        {/if}
    {/foreach}
<br />
{/foreach}
<br/>
<input type="submit" name="submit" value="更新角色"/>
<input type="hidden" name="opera" value="edit"/>
<input type="hidden" name="id" value="{$adminRole.id}"/>
</form>
<script type="text/javascript" src="js/adminRole.js"></script>
{/if}
</div><!-- contentpanel -->
{include file="library/footer.lbi"}
</body>
</html>
