{include file="library/sidebar.lbi"}
<div class="contentpanel">
{if $act eq 'list'}
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-btns">
                <a class="minimize" href="">−</a>
            </div>
            <!--            <h4 class="panel-title">添加导航条</h4>-->
            <a class="btn btn-primary" href="adPosition.php?act=add">新增广告位</a>
        </div>
        <div class="panel-body panel-body-nopadding">
            <table class="table mb30" style="width: 98%; margin: 0 auto">
                <thead>
                <tr>
                    <th>#</th>
                    <th>位置名</th>
                    <th>模板文件</th>
                    <th>类型</th>
                    <th>数量</th>
                    <th>宽度</th>
                    <th>高度</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {foreach from=$adPositions item=position name=adPositions}
                <tr>
                    <td>{$smarty.foreach.adPositions.iteration}</td>
                    <td>{$position.name}</td>
                    <td>{$position.targetTemplate}</td>
                    <td>{$position.type}</td>
                    <td>{$position.number}</td>
                    <td>{$position.width}px</td>
                    <td>{$position.height}px</td>
                    <td>
                        <a href="adPosition.php?act=edit&id={$position.id}" title="编辑"><i class="fa fa-pencil"></i></a>&nbsp;|
                        <a class="delete-row" href="adPosition.php?act=delete&id={$position.id}" title="删除"><i class="fa fa-trash-o"></i></a>
                    </td>
                </tr>
                {/foreach}
                </tbody>
            </table>

        </div><!-- panel-body -->

        <div class="panel-footer">
        </div><!-- panel-footer -->

    </div>
{/if}

{if $act eq 'add'}
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-btns">
                <a class="minimize" href="">−</a>
            </div>
            <h4 class="panel-title">添加-广告位</h4>
        </div>
        <div class="panel-body panel-body-nopadding">
            <form name="adPositionAddForm" method="POST" enctype="multipart/form-data"  class="form-horizontal form-bordered">
                <div class="form-group">
                    <label class="col-sm-3 control-label">广告位置名</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" placeholder="" name="name" value="">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">模版文件</label>
                    <div class="col-sm-2">
                        <select class="form-control " name="targetTemplate">
                            {foreach from=$templates item=t}
                                <option value="{$t}">{$t}</option>
                            {/foreach}
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">广告数量</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" placeholder="" name="number" value="3">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">是否显示</label>
                    <div class="col-sm-6">
                        <div class="radio"><label><input type="radio" name="type" value="js" checked="checked"> Javascript</label></div>
                        <div class="radio"><label><input type="radio"  name="type" value="flash"> Flash</label></div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">广告宽度</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" placeholder="" name="width" value="480">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">广告高度</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" placeholder="" name="height" value="320">
                    </div>
                </div>
                <div class="col-sm-6 col-sm-offset-3">
                    <button type="submit" class="btn btn-primary">添加</button>&nbsp;
                </div>
                <input type="hidden" name="code" value="code"/>
                <input type="hidden" name="opera" value="add"/>
            </form>
        </div><!-- panel-body -->

        <div class="panel-footer">
        </div><!-- panel-footer -->
    </div>
{/if}

{if $act eq 'edit'}
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-btns">
                <a class="minimize" href="">−</a>
            </div>
            <h4 class="panel-title">添加-广告位</h4>
        </div>
        <div class="panel-body panel-body-nopadding">
            <form name="adPositionEditForm" method="POST" enctype="multipart/form-data"  class="form-horizontal form-bordered">
                <div class="form-group">
                    <label class="col-sm-3 control-label">广告位置名</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" placeholder="" name="name" value="{$adPosition.name}">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">模版文件</label>
                    <div class="col-sm-2">
                        <select class="form-control " name="targetTemplate">
                            {foreach from=$templates item=t}
                            <option value="{$t}" {if $adPosition.targetTemplate eq $t}selected="selected"{/if}>{$t}</option>
                            {/foreach}
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">广告数量</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" placeholder="" name="number" value="{$adPosition.number}">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">类型</label>
                    <div class="col-sm-6">
                        <div class="radio"><label><input type="radio" name="type" value="js" {if $adPosition.type eq 'js'}checked="checked"{/if}/> Javascript</label></div>
                        <div class="radio"><label><input type="radio"  name="type" value="flash" {if $adPosition.type eq 'flash'}checked="checked"{/if}/> Flash</label></div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">广告宽度</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" placeholder="" name="width" value="{$adPosition.width}">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">广告高度</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" placeholder="" name="height" value="{$adPosition.height}">
                    </div>
                </div>
                <div class="col-sm-6 col-sm-offset-3">
                    <button type="submit" class="btn btn-primary">更新</button>&nbsp;
                </div>
                <input type="hidden" name="code" value="code"/>
                <input type="hidden" name="opera" value="edit"/>
                <input type="hidden" name="id" value="{$adPosition.id}" />
            </form>
        </div><!-- panel-body -->

        <div class="panel-footer">
        </div><!-- panel-footer -->
    </div>
<!--<form name="adPositionEditForm" method="POST">-->
<!--广告位置名：<input type="text" name="name" value="{$adPosition.name}"/><br/>-->
<!--模版文件：<select name="targetTemplate">-->
<!--            {foreach from=$templates item=t}-->
<!--            <option value="{$t}" {if $adPosition.targetTemplate eq $t}selected="selected"{/if}>{$t}</option>-->
<!--            {/foreach}-->
<!--          </select><br/>-->
<!--广告数量：<input type="text" name="number" value="{$adPosition.number}"/><br/>-->
<!--广告类型：<input type="radio" name="type" value="js" {if $adPosition.type eq 'js'}checked="checked"{/if}/>JavaScript-->
<!--          <input type="radio" name="type" value="flash" {if $adPosition.type eq 'flash'}checked="checked"{/if}/>Flash<br/>-->
<!--广告高度：<input type="text" name="height" value="{$adPosition.height}"/>px<br/>-->
<!--广告宽度：<input type="text" name="width" value="{$adPosition.width}"/>px<br/>-->
<!--<input type="hidden" name="code" value="{$adPosition.code}"/>-->
<!--<input type="hidden" name="opera" value="edit"/>-->
<!--<input type="hidden" name="id" value="{$adPosition.id}"/>-->
<!--<input type="submit" name="submit" value="修改广告位置"/>-->
<!--</form>-->
{/if}
</div><!-- contentpanel -->
{include file="library/footer.lbi"}

</body>
</html>