{include file="library/sidebar.lbi"}
<div class="contentpanel">
{if $act eq 'list'}
<a href="article.php?act=add">新增资讯</a>
<table>
{foreach from=$articles item=article name=articles}
<tr>
    <td>{$smarty.foreach.articles.iteration}</td>
    <td>{$article.title}</td>
    <td>{$article.articleCat}</td>
    <td>{$article.publishTime}</td>
    <td>
        <a href="../article.php?id={$article.id}">查看</a>|
        <a href="article.php?act=edit&id={$article.id}">编辑</a>|
        <a href="article.php?act=delete&id={$article.id}">删除</a>
    </td>
</tr>
{/foreach}
</table>
{/if}

{if $act eq 'cycle'}
<table>
{foreach from=$articles item=article name=articles}
<tr>
    <td>{$smarty.foreach.articles.iteration}</td>
    <td>{$article.title}</td>
    <td>{$article.articleCat}</td>
    <td>{$article.publishTime}</td>
    <td>
        <a href="../article.php?id={$article.id}">查看</a>|
        <a href="article.php?act=remove&id={$article.id}">彻底删除</a>
    </td>
</tr>
{/foreach}
</table>
{/if}

{if $act eq 'add'}
<form method="POST" name="articleAddForm"  enctype="multipart/form-data">
标题：<input type="text" name="title"/>
作者：<input type="text" name="author"/>
关键词：<input type="text" name="keywords"/>
简要描述：<textarea name="description"></textarea>
资讯分类：<select name="articleCatId">
          {foreach from=$articleCat item=cat}
            <option value="{$cat.id}">{$cat.name}</option>
          {/foreach}
          </select>
详细内容：<textarea name="content"></textarea>
自动发布：<input type="radio" name="isAutoPublish" value="0" checked="checked"/>否
          <input type="radio" name="isAutoPublish" value="1"/>是
发布时间：<input type="text" name="publishTime"/>
文章封面：<input type="file" name="img" />
<input type="submit" name="submit" value="提交"/>
<input type="hidden" name="opera" value="add"/>
</form>
<script type="text/javascript">
{literal}
KindEditor.ready(function(K)
{
    var editor1 = K.create("textarea[name='content']", {
    	cssPath : '../plugins/kindeditor/plugins/code/prettify.css',
		uploadJson : '../plugins/kindeditor/upload_json.php',
		fileManagerJson : '../plugins/kindeditor/file_manager_json.php',
		allowFileManager : true,
		afterCreate : function() {
			var self = this;
            K.ctrl(document, 13, function() {
				self.sync();
				K('form[name=articleAddForm]')[0].submit();
			});
			K.ctrl(self.edit.doc, 13, function() {
				self.sync();
				K('form[name=articleAddForm]')[0].submit();
			});
		}
	});		
    prettyPrint();		
});
{/literal}
</script>
{/if}

{if $act eq 'edit'}
<form method="POST" name="articleEditForm"  enctype="multipart/form-data">
标题：<input type="text" name="title" value="{$article.title}"/>
作者：<input type="text" name="author" value="{$article.author}"/>
关键词：<input type="text" name="keywords" value="{$article.keywords}"/>
简要描述：<textarea name="description">{$article.description}</textarea>
资讯分类：<select name="articleCatId">
          {foreach from=$articleCat item=cat}
            <option value="{$cat.id}" {if $article.articleCatId eq $cat.id}selected="selected"{/if}>{$cat.name}</option>
          {/foreach}
          </select>
详细内容：<textarea name="content">{$article.content}</textarea>
自动发布：<input type="radio" name="isAutoPublish" value="0" {if $article.isAutoPublish eq 0}checked="checked"{/if}/>否
          <input type="radio" name="isAutoPublish" value="1" {if $article.isAutoPublish eq 1}checked="checked"{/if}/>是
发布时间：<input type="text" name="publishTime" value="{$article.publishTime}"/>
封面：<input type="file" name="img" /><br />
{if $article.img}
<img src="{$article.img}" />
{/if}
<input type="submit" name="submit" value="提交修改"/>
<input type="hidden" name="opera" value="edit"/>
<input type="hidden" name="id" value="{$article.id}"/>
</form>
<script>
{literal}
	KindEditor.ready(function(K) {
		var editor1 = K.create('textarea[name="content"]', {
			cssPath : '../plugins/kindeditor/plugins/code/prettify.css',
			uploadJson : '../plugins/kindeditor/upload_json.php',
			fileManagerJson : '../plugins/kindeditor/file_manager_json.php',
			allowFileManager : true,
			afterCreate : function() {
				var self = this;
                K.ctrl(document, 13, function() {
					self.sync();
					K('form[name=articleAddForm]')[0].submit();
				});
				K.ctrl(self.edit.doc, 13, function() {
					self.sync();
					K('form[name=articleAddForm]')[0].submit();
				});
			}
		});
		prettyPrint();		
    });
{/literal}
</script>

{/if}
</div><!-- contentpanel -->
{include file="library/footer.lbi"}
