{include file="library/sidebar.lbi"}
<div class="contentpanel">
{if $act eq 'list'}
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-btns">
                <a class="minimize" href="">−</a>
            </div>
            <!--            <h4 class="panel-title">添加导航条</h4>-->
            <a class="btn btn-primary" href="article.php?act=add">新增资讯</a>
            <a class="btn btn-primary" href="article.php?act=cycle">回收站</a>
        </div>
        <div class="panel-body panel-body-nopadding">
            <table class="table mb30" style="width: 98%; margin: 0 auto">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>标题</th>
                        <th>封面</th>
                        <th>分类</th>
                        <th>作者</th>
                        <th>发布时间</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                {foreach from=$articles item=article name=articles}
                    <tr>
                        <td>{$smarty.foreach.articles.iteration}</td>
                        <td>{$article.title}</td>
                        <td>{if $article.img_shortcut}<a href="#" data-trigger="manual" class="bootstrap-popover" data-original-title="" title=""><img alt="{$article.img}" src="{$article.img_shortcut}"/></a>{/if}</td>
                        <td>{$article.articleCat}</td>
                        <td>{$article.author}</td>
                        <td>{$article.publishTime}</td>
                        <td>
                            <a href="../article.php?id={$article.id}" title="查看"><i class="fa fa-eye"></i></a>&nbsp;|
                            <a href="article.php?act=edit&id={$article.id}" title="编辑"><i class="fa fa-pencil"></i></a>&nbsp;|
                            <a class="delete-row" href="article.php?act=delete&id={$article.id}" title="删除"><i class="fa fa-trash-o"></i></a>
                        </td>
                    </tr>
                {/foreach}
                </tbody>
            </table>

        </div><!-- panel-body -->

        <div class="panel-footer">
        </div><!-- panel-footer -->

    </div>

{/if}

{if $act eq 'cycle'}
<table>
{foreach from=$articles item=article name=articles}
<tr>
    <td>{$smarty.foreach.articles.iteration}</td>
    <td>{$article.title}</td>
    <td>{$article.articleCat}</td>
    <td>{$article.publishTime}</td>
    <td>
        <a href="../article.php?id={$article.id}">查看</a>|
        <a href="article.php?act=remove&id={$article.id}">彻底删除</a>
    </td>
</tr>
{/foreach}
</table>
{/if}

{if $act eq 'add'}
<form method="POST" name="articleAddForm"  enctype="multipart/form-data">
标题：<input type="text" name="title"/>
作者：<input type="text" name="author"/>
关键词：<input type="text" name="keywords"/>
简要描述：<textarea name="description"></textarea>
资讯分类：<select name="articleCatId">
          {foreach from=$articleCat item=cat}
            <option value="{$cat.id}">{$cat.name}</option>
          {/foreach}
          </select>
详细内容：<textarea name="content"></textarea>
自动发布：<input type="radio" name="isAutoPublish" value="0" checked="checked"/>否
          <input type="radio" name="isAutoPublish" value="1"/>是
发布时间：<input type="text" name="publishTime"/>
文章封面：<input type="file" name="img" />
<input type="submit" name="submit" value="提交"/>
<input type="hidden" name="opera" value="add"/>
</form>
<script type="text/javascript" src="js/plugins/kindeditor/kindeditor-all-min.js"></script>
<script type="text/javascript">
{literal}
KindEditor.ready(function(K)
{
    var editor1 = K.create("textarea[name='content']", {
    	cssPath : '../plugins/kindeditor/plugins/code/prettify.css',
		uploadJson : '../plugins/kindeditor/php/upload_json.php',
		fileManagerJson : '../plugins/kindeditor/php/file_manager_json.php',
		allowFileManager : true,
		afterCreate : function() {
			var self = this;
            K.ctrl(document, 13, function() {
				self.sync();
				K('form[name=articleAddForm]')[0].submit();
			});
			K.ctrl(self.edit.doc, 13, function() {
				self.sync();
				K('form[name=articleAddForm]')[0].submit();
			});
		}
	});		
    prettyPrint();		
});
{/literal}
</script>
{/if}

{if $act eq 'edit'}
<form method="POST" name="articleEditForm"  enctype="multipart/form-data">
标题：<input type="text" name="title" value="{$article.title}"/>
作者：<input type="text" name="author" value="{$article.author}"/>
关键词：<input type="text" name="keywords" value="{$article.keywords}"/>
简要描述：<textarea name="description">{$article.description}</textarea>
资讯分类：<select name="articleCatId">
          {foreach from=$articleCat item=cat}
            <option value="{$cat.id}" {if $article.articleCatId eq $cat.id}selected="selected"{/if}>{$cat.name}</option>
          {/foreach}
          </select>
详细内容：<textarea name="content">{$article.content}</textarea>
自动发布：<input type="radio" name="isAutoPublish" value="0" {if $article.isAutoPublish eq 0}checked="checked"{/if}/>否
          <input type="radio" name="isAutoPublish" value="1" {if $article.isAutoPublish eq 1}checked="checked"{/if}/>是
发布时间：<input type="text" name="publishTime" value="{$article.publishTime}"/>
封面：<input type="file" name="img" /><br />
{if $article.img}
<img src="{$article.img}" />
{/if}
<input type="submit" name="submit" value="提交修改"/>
<input type="hidden" name="opera" value="edit"/>
<input type="hidden" name="id" value="{$article.id}"/>
</form>
    <script type="text/javascript" src="js/plugins/kindeditor/kindeditor-all-min.js"></script>
    <script type="text/javascript">
        {literal}
        KindEditor.ready(function(K)
        {
            var editor1 = K.create("textarea[name='content']", {
                cssPath : '../plugins/kindeditor/plugins/code/prettify.css',
                uploadJson : '../plugins/kindeditor/php/upload_json.php',
                fileManagerJson : '../plugins/kindeditor/php/file_manager_json.php',
                allowFileManager : true,
                afterCreate : function() {
                    var self = this;
                    K.ctrl(document, 13, function() {
                        self.sync();
                        K('form[name=articleeditForm]')[0].submit();
                    });
                    K.ctrl(self.edit.doc, 13, function() {
                        self.sync();
                        K('form[name=articleeditForm]')[0].submit();
                    });
                }
            });
            prettyPrint();
        });
        {/literal}
    </script>

{/if}
</div><!-- contentpanel -->
{include file="library/footer.lbi"}
<script type="text/javascript" src="js/article.js"></script>
</body>
</html>