{include file="library/sidebar.lbi"}
<div class="contentpanel">
{if $act eq 'list'}
    <a href="carousel.php?act=add">添加轮播图片</a>
    <table>
    {foreach from=$carousels item=carousel}
        <tr>
            <td><a href="{$carousel.img}" target="_blank"><img src="{$carousel.img_shortcut}" width="192" height="45" /></a></td>
            <td>{$carousel.add_time}</td>
            <td>
                <a href="carousel.php?act=edit&id={$carousel.id}">编辑</a>|
                <a href="carousel.php?act=delete&id={$carousel.id}">删除</a>
            </td>
        </tr>
    {/foreach}
    </table>
{/if}
{if $act eq 'add'}
<form name="carouselAddForm" method="post" enctype="multipart/form-data">
图片：<input type="file" name="img" /><br />
顺序：<input type="text" name="orderView" value="50" /><br />
    <input type="submit" name="submit" name="添加轮播图"/>
    <input type="hidden" name="opera" value="add"/>
</form>
{/if}
{if $act eq 'edit'}
<form name="carouselEditForm" method="post" enctype="multipart/form-data">
    图片：<input type="file" name="img" /><br />
    {if $carousel.img}
    <img width="192" height="45" src="{$carousel.img_shortcut}" /><br />
    {/if}
    顺序：<input type="text" name="orderView" value="{$carousel.orderView}" /><br />
    <input type="submit" name="submit" name="更新轮播图"/>
    <input type="hidden" name="opera" value="edit"/>
</form>
{/if}
</div><!-- contentpanel -->
{include file="library/footer.lbi"}
