<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="images/favicon.png" type="image/png">

    <title>{$pageTitle}</title>

    <link href="css/style.default.css" rel="stylesheet">
    <link href="css/jquery.datatables.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <script src="js/jquery-1.11.1.min.js"></script>
</head>
{include file="library/sidebar.lbi"}
<div class="contentpanel">
{if $act eq 'list'}
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-btns">
                <a class="minimize" href="">−</a>
            </div>
            <!--            <h4 class="panel-title">添加导航条</h4>-->
            <a class="btn btn-primary" href="distributor.php?act=add">新增经销商</a>
        </div>
        <div class="panel-body panel-body-nopadding">
            <table id="distributor-list" class="table mb30" style="width: 98%; margin: 0 auto">
                <thead>
                <tr>
                    <th>#</th>
                    <th>经销商</th>
                    <th>联系人</th>
                    <th>手机</th>
                    <th>地址</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                    {foreach from=$distributors item=distributor name=distributors}
                    <tr>
                        <td>{$smarty.foreach.distributors.iteration}</td>
                        <td>{$distributor.name}</td>
                        <td>{$distributor.contact}</td>
                        <td>{$distributor.phone}</td>
                        <td>{$distributor.area}&nbsp;&nbsp;{$distributor.address}</td>
                        <td>
                            <a href="distributor.php?act=edit&id={$distributor.id}" title="编辑"><i class="fa fa-pencil"></i></a>&nbsp;|
                            <a onclick="javascript:if(confirm('确认要删除？')) return true; else return false;" class="delete-row" href="distributor.php?act=delete&id={$distributor.id}" title="删除"><i class="fa fa-trash-o"></i></a>
                        </td>
                    </tr>
                    {/foreach}
                </tbody>
            </table>

        </div><!-- panel-body -->

        <div class="panel-footer">
        </div><!-- panel-footer -->

    </div>
    <script src="js/jquery.datatables.min.js"></script>
{/if}
{if $act eq 'add'}
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-btns">
                <a class="minimize" href="">−</a>
            </div>
<!--            <h4 class="panel-title">添加-经销商</h4>-->
            <a class="btn btn-primary" href="distributor.php">返回</a>
        </div>
        <div class="panel-body panel-body-nopadding">
            <form name="distributorAddForm" method="POST"  class="form-horizontal form-bordered">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <div class="panel-btns">
                                    <a class="minimize" href="">-</a>
                                    <h4 class="panel-title">地图信息</h4>
                                </div>
                            </div>
                            <div class="panel-body">
                                <div class="form-group">
                                    <label class="control-label col-sm-2">地区</label>
                                    <div class="col-sm-3">
                                        <select id="province" name="province" class="form-control">
                                            <option value="0">请选择</option>
                                        {foreach from=$provinces item=province}
                                            <option value="{$province.ProvinceID}">{$province.ProvinceName}</option>
                                        {/foreach}
                                        </select>
                                    </div>
                                    <div class="col-sm-3">
                                        <select id="city" name="city" class="form-control">
                                            <option value="0">请选择</option>
                                        </select>
                                    </div>
                                    <div class="col-sm-3">
                                        <select id="district" name="district" class="form-control">
                                            <option value="0">请选择</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-2">具体地址:</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" placeholder="" name="address" value="" />
                                    </div>
                                    <label for="checkbox" class="col-sm-2 control-label"></label>
                                    <div class="col-sm-5">
                                        <div class="checkbox block"><label><input type="checkbox" value="1" class="form-control" id="search-on"/>开启检索</label></div>
                                    </div>

                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">经度</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" name="lng-show" disabled=true value="0.0"/>
                                    </div>
                                    <label class="col-sm-2 control-label">纬度</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" name="lat-show" disabled=true value="0.0"/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-12">
                                        <div id="baidu-map">

                                        </div>
                                        <p>点击地图获取当前经纬度</p>
                                    </div>
                                </div>
                            </div><!-- panel-body -->
                            <div class="panel-footer">
                                <div class="col-sm-6 col-sm-offset-3">
                                    <button type="submit" class="btn btn-primary">提交</button>&nbsp;
                                </div>
                                <input type="hidden" name="opera" value="add"/>
                                <input type="hidden" name="lng" value="0.0"/>
                                <input type="hidden" name="lat" value="0.0"/><br />
                            </div><!-- panel-footer -->
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <div class="panel-btns">
                                    <a class="minimize" href="">-</a>
                                    <h4 class="panel-title">基础信息</h4>
                                </div>
                            </div>
                            <div class="panel-body" style="">
                                <div class="form-group">
                                    <label class="control-label">经销商名称:</label>
                                    <div class="col-sm-12">
                                        <input type="text" class="form-control" placeholder="" name="name" value="" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label">联系人:</label>
                                    <div class="col-sm-12">
                                        <input type="text" class="form-control" placeholder="" name="contact" value="" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label">手机:</label>
                                    <div class="col-sm-12">
                                        <input type="text" class="form-control" placeholder="" name="phone" value="" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label">授权码:</label>
                                    <div class="col-sm-12">
                                        <input type="text" class="form-control" placeholder="" name="auth_code" value="" />
                                    </div>
                                </div>

                            </div><!-- panel-body -->
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="panel-footer">
        </div><!-- panel-footer -->

    </div>
    <script type="text/javascript">
        var data_cities = {$json_cities};
        var data_districts = {$json_districts};
        var map_init = {$map_init};

    </script>
    <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=zos6EyqBZkweV9bUq7MF3brX"></script>
    <script type="text/javascript" src="js/distributor.js"></script>
{/if}
{if $act eq 'edit'}
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-btns">
                <a class="minimize" href="">−</a>
            </div>

<!--            <h4 class="panel-title">编辑-{$distributor.name}</h4>-->
            <a class="btn btn-primary" href="distributor.php">返回</a>
        </div>
        <div class="panel-body panel-body-nopadding">
            <form name="distributorEidtForm" method="POST"  class="form-horizontal form-bordered">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <div class="panel-btns">
                                    <a class="minimize" href="">-</a>
                                    <h4 class="panel-title">地图信息</h4>
                                </div>
                            </div>
                            <div class="panel-body">
                                <div class="form-group">
                                    <label class="control-label col-sm-2">地区</label>
                                    <div class="col-sm-3">
                                        <select id="province" name="province" class="form-control">
                                            <option value="0">请选择</option>
                                            {foreach from=$provinces item=province}
                                                {if $province.ProvinceID eq $distributor.ProvinceID}
                                            <option value="{$province.ProvinceID}" selected="selected">{$province.ProvinceName}</option>
                                                {else}
                                            <option value="{$province.ProvinceID}">{$province.ProvinceName}</option>
                                                {/if}
                                            {/foreach}
                                        </select>
                                    </div>
                                    <div class="col-sm-3">
                                        <select id="city" name="city" class="form-control">
                                            <option value="0">请选择</option>
                                            {foreach from=$cities[$distributor.ProvinceID] item=city}
                                                {if $city.CityID eq $distributor.CityID}
                                            <option value="{$city.CityID}" selected="selected">{$city.CityName}</option>
                                                {else}
                                            <option value="{$city.CityID}">{$city.CityName}</option>
                                                {/if}
                                            {/foreach}
                                        </select>
                                    </div>
                                    <div class="col-sm-3">
                                        <select id="district" name="district" class="form-control">
                                            <option value="0">请选择</option>
                                            {foreach from=$districts[$distributor.CityID] item=district}
                                                {if $district.DistrictID eq $distributor.DistrictID}
                                            <option value="{$district.DistrictID}" selected="selected">{$district.DistrictName}</option>
                                                {else}
                                            <option value="{$district.DistrictID}">{$district.DistrictName}</option>
                                                {/if}
                                            {/foreach}
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-2">具体地址:</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" placeholder="" name="address" value="{$distributor.address}" />
                                    </div>
                                    <label for="checkbox" class="col-sm-2 control-label"></label>
                                    <div class="col-sm-5">
                                        <div class="checkbox block"><label><input type="checkbox" value="1" class="form-control" id="search-on"/>开启检索</label></div>
                                    </div>

                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">经度</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" name="lng-show" disabled=true value="{$distributor.lng}"/>
                                    </div>
                                    <label class="col-sm-2 control-label">纬度</label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" name="lat-show" disabled=true value="{$distributor.lat}"/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-12">
                                        <div id="baidu-map">

                                        </div>
                                        <p>点击地图获取当前经纬度</p>
                                    </div>
                                </div>
                            </div><!-- panel-body -->
                            <div class="panel-footer">
                                <div class="col-sm-6 col-sm-offset-3">
                                    <button type="submit" class="btn btn-primary">提交</button>&nbsp;
                                </div>
                                <input type="hidden" name="opera" value="edit"/>
                                <input type="hidden" name="lng" value="{$distributor.lng}"/>
                                <input type="hidden" name="lat" value="{$distributor.lat}"/>
                                <input type="hidden" name="id" value="{$distributor.id}" />
                            </div><!-- panel-footer -->
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <div class="panel-btns">
                                    <a class="minimize" href="">-</a>
                                    <h4 class="panel-title">基础信息</h4>
                                </div>
                            </div>
                            <div class="panel-body" style="">
                                <div class="form-group">
                                    <label class="control-label">经销商名称:</label>
                                    <div class="col-sm-12">
                                        <input type="text" class="form-control" placeholder="" name="name" value="{$distributor.name}" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label">联系人:</label>
                                    <div class="col-sm-12">
                                        <input type="text" class="form-control" placeholder="" name="contact" value="{$distributor.contact}" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label">手机:</label>
                                    <div class="col-sm-12">
                                        <input type="text" class="form-control" placeholder="" name="phone" value="{$distributor.phone}" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label">授权码:</label>
                                    <div class="col-sm-12">
                                        <input type="text" class="form-control" placeholder="" name="auth_code" value="{$distributor.authCode}" />
                                    </div>
                                </div>

                            </div><!-- panel-body -->
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="panel-footer">
        </div><!-- panel-footer -->

    </div>
    <script type="text/javascript">
        var data_cities = {$json_cities};
        var data_districts = {$json_districts};
        var map_init = {$map_init};

    </script>
    <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=zos6EyqBZkweV9bUq7MF3brX"></script>
    <script type="text/javascript" src="js/distributor.js"></script>
{/if}

</div><!-- contentpanel -->
{include file="library/footer.lbi"}
<script type="text/javascript" src="js/distributor.js"></script>
</body>
</html>