{include file="library/sidebar.lbi"}
<div class="contentpanel">
{if $act eq 'list'}
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-btns">
                <a class="minimize" href="">−</a>
            </div>
            <!--            <h4 class="panel-title">添加导航条</h4>-->
            <a class="btn btn-primary" href="distributor.php?act=add">新增经销商</a>
        </div>
        <div class="panel-body panel-body-nopadding">
            <table class="table mb30" style="width: 98%; margin: 0 auto">
                <thead>
                <tr>
                    <th>#</th>
                    <th>经销商</th>
                    <th>联系人</th>
                    <th>手机</th>
                    <th>地址</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                    {foreach from=$distributors item=distributor name=distributors}
                    <tr>
                        <td>{$smarty.foreach.distributors.iteration}</td>
                        <td>{$distributor.name}</td>
                        <td>{$distributor.contact}</td>
                        <td>{$distributor.phone}</td>
                        <td>{$distributor.area}&nbsp;&nbsp;{$distributor.address}</td>
                        <td>
                            <a href="distributor.php?act=edit&id={$distributor.id}" title="编辑"><i class="fa fa-pencil"></i></a>&nbsp;|
                            <a class="delete-row" href="distributor.php?act=delete&id={$distributor.id}" title="删除"><i class="fa fa-trash-o"></i></a>
                        </td>
                    </tr>
                    {/foreach}
                </tbody>
            </table>

        </div><!-- panel-body -->

        <div class="panel-footer">
        </div><!-- panel-footer -->

    </div>
{/if}
{if $act eq 'add'}
    <form name="distributorAddForm" method="POST">
        经销商名称：<input type="text" name="name" /><br/>
        联系人：<input type="text" name="contact" /><br/>
        联系电话：<input type="text" name="phone" /><br/>
        授权码：<input type="text" name="auth_code" /><br />
        地区：
        <select id="province" name="province">
            <option value="0">请选择</option>
        {foreach from=$provinces item=province}
            <option value="{$province.ProvinceID}">{$province.ProvinceName}</option>
        {/foreach}
        </select>&nbsp;&nbsp;
        <select id="city" name="city">
            <option value="0">请选择</option>
        </select>&nbsp;&nbsp;
        <select id="district" name="district">
            <option value="0">请选择</option>
        </select><br />
        具体地址：<input type="text" name="address" />&nbsp;
        <input type="checkbox" value="1" id="search-on"/>开启检索<br/>
        经度：<input type="text" name="lng-show" disabled=true value="0.0"/>&nbsp;&nbsp;
        纬度：<input type="text" name="lat-show" disabled=true value="0.0"/><br />
        <input type="submit" name="submit" value="添加经销商"/>
        <input type="hidden" name="opera" value="add"/>
        <input type="hidden" name="lng" value="0.0"/>&nbsp;&nbsp;
        <input type="hidden" name="lat" value="0.0"/><br />
    </form>
    <div id="baidu-map">

    </div>
    <p>点击地图获取当前经纬度</p>
    <script type="text/javascript">
        var data_cities = {$json_cities};
        var data_districts = {$json_districts};
        var map_init = {$map_init};

    </script>
    <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=zos6EyqBZkweV9bUq7MF3brX"></script>
    <script type="text/javascript" src="js/distributor.js"></script>
{/if}
{if $act eq 'edit'}
    <form name="distributorEditForm" method="POST">
        经销商名称：<input type="text" name="name" value="{$distributor.name}"/><br/>
        联系人：<input type="text" name="contact" value="{$distributor.contact}" /><br/>
        联系电话：<input type="text" name="phone" value="{$distributor.phone}" /><br/>
        授权码：<input type="text" name="auth_code" value="{$distributor.authCode}" /><br />
        地区：
        <select id="province" name="province">
            <option value="0">请选择</option>
            {foreach from=$provinces item=province}
                {if $province.ProvinceID eq $distributor.ProvinceID}
            <option value="{$province.ProvinceID}" selected="selected">{$province.ProvinceName}</option>
                {else}
            <option value="{$province.ProvinceID}">{$province.ProvinceName}</option>
                {/if}
            {/foreach}
        </select>&nbsp;&nbsp;
        <select id="city" name="city">
            <option value="0">请选择</option>
            {foreach from=$cities[$distributor.ProvinceID] item=city}
                {if $city.CityID eq $distributor.CityID}
            <option value="{$city.CityID}" selected="selected">{$city.CityName}</option>
                {else}
            <option value="{$city.CityID}">{$city.CityName}</option>
                {/if}
            {/foreach}
        </select>&nbsp;&nbsp;
        <select id="district" name="district">
            <option value="0">请选择</option>
            {foreach from=$districts[$distributor.CityID] item=district}
                {if $district.DistrictID eq $distributor.DistrictID}
            <option value="{$district.DistrictID}" selected="selected">{$district.DistrictName}</option>
                {else}
            <option value="{$district.DistrictID}">{$district.DistrictName}</option>
                {/if}
            {/foreach}
        </select><br />
        具体地址：<input type="text" name="address" value="{$distributor.address}"/><br/>
        经度：<input type="text" name="lng-show" disabled=true value="{$distributor.lng}"/>&nbsp;&nbsp;
        纬度：<input type="text" name="lat-show" disabled=true value="{$distributor.lat}"/><br />
        <input type="submit" name="submit" value="编辑经销商"/>
        <input type="hidden" name="opera" value="edit"/>
        <input type="hidden" name="lng" value="{$distributor.lng}"/>&nbsp;&nbsp;
        <input type="hidden" name="lat" value="{$distributor.lat}"/><br />
        <input type="hidden" name="id" value="{$distributor.id}" ><br />
    </form>
    <div id="baidu-map">

    </div>
    <p>点击地图获取当前经纬度</p>
    <script type="text/javascript">
        var data_cities = {$json_cities};
        var data_districts = {$json_districts};
        var map_init = {$map_init};

    </script>
    <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=zos6EyqBZkweV9bUq7MF3brX"></script>
    <script type="text/javascript" src="js/distributor.js"></script>
{/if}

</div><!-- contentpanel -->
{include file="library/footer.lbi"}
</body>
</html>