<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
<title>{$pageTitle}</title>
<link rel="stylesheet" type="text/css" href="css/style.css"/>
<script type="text/javascript" src="js/xajax.js"></script>
<script type="text/javascript" src="js/index.js"></script>
</head>
<body>
{foreach from=$menus item=menu}
<a href="{$menu.url}">{$menu.title}</a><br/>
{/foreach}
</body>
</html>
