<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
<meta http-equiv="refresh" content="{$time}; url={$link}"/>
<title>{$pageTitle}</title>
<link rel="stylesheet" type="text/css" href="css/style.css"/>
<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css"/>
<script type="text/javascript" src="js/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="js/bootstrap.min.js"></script>
</head>
<body>
<!--{$message}-->
<!--{if $links}-->
<!--{foreach from=$links item=a}-->
<!--<a href="{$a.link}" title="{$a.alt}">{$a.alt}</a>-->
<!--{/foreach}-->
<!--{/if}-->
<div aria-hidden="false" data-backdrop="static" aria-labelledby="mySmallModalLabel" role="dialog" tabindex="-1" class="modal fade bs-example-modal-static in" style="display: block;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">系统消息</h4>
            </div>
            <div class="modal-body">
                <span>{$message}</span><br /><br /><br />
                {foreach from=$links item=a}
                <a href="{$a.link}" title="{$a.alt}">{$a.alt}</a>
                {/foreach}
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
{literal}
$(function(){
    $('.modal').modal();
});
{/literal}
</script>
</body>
</html>
