<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="images/favicon.png" type="image/png">

    <title>{$pageTitle}</title>

    <link href="css/style.default.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <script src="js/jquery-1.11.1.min.js"></script>
</head>
{include file="library/sidebar.lbi"}
<div class="contentpanel">
{if $act eq 'list'}
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-btns">
                <a class="minimize" href="">−</a>
            </div>
            <h4 class="panel-title">系统信息列表</h4>
        </div>
        <div class="panel-body panel-body-nopadding">
            <table>
                {foreach from=$sysconf item=conf}
                <div class="form-group">
                    <label class="col-sm-3 control-label">{$conf.name}</label>
                    <div class="col-sm-6">
            <span>
            {if $conf.type eq 'text' or $conf.type eq 'textarea'}
                {$conf.value}
            {/if}

            {if $conf.type eq 'file'}
                <img src="./../{$conf.value}"/>
            {/if}

            {if $conf.type eq 'radio'}
                {if $conf.value}
                是
                {else}
                否
                {/if}
            {/if}
            </span>
                    </div>
                    <div class="col-sm-3">
                        <a href="sysconf.php?act=edit&key={$conf.key}">编辑</a>
                    </div>
                </div>
                {/foreach}
            </table>
        </div><!-- panel-body -->

        <div class="panel-footer">
        </div><!-- panel-footer -->

    </div>

{/if}

{if $act eq 'add'}
<form name="sysconfAddForm" method="POST" enctype="multipart/form-data">
显示名：<input type="text" name="name"/>
key：<input type="text" name="key"/>
类型：<input type="radio" name="type" value="text"/>文本
      <input type="radio" name="type" value="file"/>图片
      <input type="radio" name="type" value="radio"/>布尔值
取值：<input type="text" name="value"/>
图片：<input type="file" name="value"/>
<input type="submit" name="submit" value="添加"/>
<input type="hidden" name="opera" value="add"/>
</form>
{/if}

{if $act eq 'edit'}<div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-btns">
                <a class="minimize" href="">−</a>
            </div>
            <h4 class="panel-title">编辑-{$conf.name}</h4>
        </div>
        <div class="panel-body panel-body-nopadding">
            <form class="form-horizontal form-bordered" name="sysconfEditForm" method="POST" enctype="multipart/form-data">
                <div class="form-group">
                    <label class="col-sm-3 control-label">{$conf.name}</label>
                    <div class="col-sm-6">
                        {if $conf.type eq 'text'}

                        <input class="form-control" type="{$conf.type}" name="value" {if $conf.type eq "text"}value="{$conf.value}"{/if}/>
                        {/if}
                        {if $conf.type eq 'file'}
                        <input type="{$conf.type}" name="value" {if $conf.type eq "text"}value="{$conf.value}"{/if}/>
                        {/if}
                        {if $conf.type eq 'radio'}
                        <div class="col-sm-6">
                            <div class="radio"><label><input type="radio" name="value" value="0" {if $conf.value eq 0}checked="checked"{/if}/>否</label></div>
                            <div class="radio"><label><input type="radio" name="value" value="1" {if $conf.value}checked="checked"{/if}/>是</label></div>
                        </div>
                        {/if}

                        {if $conf.type eq 'textarea'}
                        <textarea name="value">{$conf.value}</textarea>
                        {/if}
                        <input class="form-control" type="hidden" name="key" value="{$conf.key}"/>
                        <input class="form-control" type="hidden" name="type" value="{$conf.type}"/>
                        <input class="form-control" type="hidden" name="opera" value="edit"/>
                        {if $conf.type eq "file"}
                        <img src="{$conf.value}"/>
                        {/if}
                    </div>
                </div>
                <div class="col-sm-6 col-sm-offset-3">
                    <button type="submit" class="btn btn-primary">修改</button>&nbsp;
                </div>
            </form>
        </div><!-- panel-body -->

        <div class="panel-footer">
        </div><!-- panel-footer -->

    </div>

{/if}
</div><!-- contentpanel -->
{include file="library/footer.lbi"}
</body>
</html>