<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>{$pageTitle}-{$siteName}</title>
<meta name="keywords" content="{$keywords}"/>
<meta name="description" content="{$description}"/>
<link href="css/style.css" type="text/css" rel="stylesheet"/>
<link rel="shortcut icon" type="image/x-icon" href="{$domain}/favoriate.ico" media="screen"/>
<script type="text/javascript" src="js/jquery.js?v=1.0.0"></script>
<script type="text/javascript" src="js/article.js?v=1.0.0"></script>
<meta name="author" content="Winsen"/>
</head>
<body>
{include file="library/header.lbi"}
{if $display eq 'article'}
<div class="content ur-here">
{$LANG.urHere}:
{foreach from=$urHere item=tag}
{if $tag.link eq ''}
{$tag.title}
{else}
<a href="{$tag.link}" title="{$tag.title}">{$tag.title}></a>
{/if}
{/foreach}
</div>
<div class="content clearfix mt">
	<div class="article-left">
		<h2 class="article-cat-title">{$LANG.articleCat}</h2>
		<ul class="article-cat">
		{foreach from=$articleCatList item=cat}
		<li><a href="{'articleCat'|build_url:$cat}" title="{$cat.name}" {if $cat.id eq $article.articleCatId}class="cur"{/if}>{$cat.name}</a></li>
		{/foreach}
		</ul>
	</div>
	<div class="article-right">
		<h2 class="article-title">{$article.title}</h2>
		<p class="article-notice">
			<span class="article-author">{$LANG.author}:&nbsp;{$article.author}</span>
			<span class="article-date">{$LANG.publishTime}:&nbsp;{$article.publishTime}</span>
			<span class="article-size">
				{$LANG.fontSize}:
				<a href="javascript:mini();" id="mini">小</a>
				<a href="javascript:normal();" id="normal">中</a>
				<a href="javascript:big();" id="big">大</a>
			</span>
		</p>
		<div class="article-content" id="article-content">
		{$article.content}
		</div>
		<p class="article-toolbar">
			{if $pre}
			<a href="{'article'|build_url:$pre.id}" title="{$pre.title}" class="article-prev">{$LANG.prevArticle}:&nbsp;{$pre.title}</a>
			{else}
			<span class="article-prev">{$LANG.prevArticle}:&nbsp;{$LANG.notFoundArticle}</span>
			{/if}
			
			{if $next}
			<a href="{'article'|build_url:$next.id}" title="{$next.title}" class="article-next">{$LANG.nextArticle}:&nbsp;{$next.title}</a>
			{else}
			<span class="article-next">{$LANG.nextArticle}:&nbsp;{$LANG.notFoundArticle}</span>
			{/if}
		</p>
	</div>
</div>
{/if}

{if $display eq 'notFound'}
<div class="content clearfix">
你所查看的文章不存在，以下是最近更新的5篇文章
</div>
{/if}
{include file="library/footer.lbi"}
</body>
</html>
