<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>{$pageTitle}-{$siteName}</title>
<meta name="keywords" content="{$keywords}"/>
<meta name="description" content="{$description}"/>
<link href="css/style.css" type="text/css" rel="stylesheet"/>
<link rel="shortcut icon" type="image/x-icon" href="{$domain}/favoriate.ico" media="screen"/>
<script type="text/javascript" src="js/jquery.js?v=1.0.0"></script>
<script type="text/javascript" src="js/index.js?v=1.0.0"></script>
<meta name="author" content="Winsen"/>
</head>
<body>
{include file="library/header.lbi"}

<div class="banner_bg"></div>
<div class="g-menu">
    <div class="m-menu">
        <p>
            {$LANG.urHere}:
            {foreach from=$urHere item=tag}
            {if $tag.link eq ''}
            {$tag.title}
            {else}
            <a href="{$tag.link}">{$tag.title}</a><span>&gt;</span>
            {/if}
            {/foreach}
        </p>
    </div>
</div>
<div class="main">
    <div class="nav_side">
        <h3><span>{$cat.name}</span></h3>
        <ul>
        {foreach from=$categoryList item=category}
            <li><a href="{'articleCat'|buildUrl:$category}">{$category.name}</a></li>
        {/foreach}
        </ul>
    </div>
    <div class="category_list">
        {foreach from=$articles item=article}
        <div class="list_info">
            <div class="post_header">
                <h3 class="post_title"><a href="{'article'|buildUrl:$article}">{$article.title}</a></h3>
                <span class="post_date">发布时间：{$article.publishTime}</span>
                <div class="clear"></div>
            </div>
            <div class="post_summary">
                <p>{$article.description}…</p>
            </div>
        </div>
        {/foreach}
        {include file="library/pager.lbi"}
    </div>
</div>
{include file="library/footer.lbi"}
</body>
</html>
