<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>{$pageTitle}-{$siteName}</title>
<meta name="keywords" content="{$keywords}"/>
<meta name="description" content="{$description}"/>
<link href="css/style.css" type="text/css" rel="stylesheet"/>
<link rel="shortcut icon" type="image/x-icon" href="{$domain}/favoriate.ico" media="screen"/>
<script type="text/javascript" src="js/jquery.js?v=1.0.0"></script>
<script type="text/javascript" src="js/article.js?v=1.0.0"></script>
<meta name="author" content="Winsen"/>
</head>
<body>
{include file="library/header.lbi"}
<div class="g-menu">
    <div class="m-menu">
        <p>
            {$LANG.urHere}:
            {foreach from=$urHere item=tag}
            {if $tag.link eq ''}
            {$tag.title}
            {else}
            <a target="_blank" href="{$tag.link}">{$tag.title}</a><span>&gt;</span>
            {/if}
            {/foreach}
        </p>
    </div>
</div>
<div class="main">
    <div class="nav_side">
        <h3><span>{$cat.name}</span></h3>
        <ul>
            {foreach from=$articleCatList item=category}
            <li><a href="{'articleCat'|buildUrl:$category}">{$category.name}</a></li>
            {/foreach}
        </ul>
    </div>
    <div class="container_r">
        <h1 class="article_title">{$article.title}</h1>
        <div class="article_info">
            <div class="name">作者：{$article.author}</div>
            <div class="time">发布时间：{$article.publishTime}</div>
            <dl class="textShare">
                <dt>分享到:</dt>
                <dd>
                    <!-- 分享代码开始 -->
                    <div class="bshare-custom icon-medium"><div class="bsPromo bsPromo2"></div>
                        <div class="bsPromo bsPromo2"></div>
                        <a href="javascript:void(0);" class="bshare-weixin" title="分享到微信"></a>
                        <a class="bshare-sinaminiblog" title="分享到新浪微博"></a>
                        <a href="javascript:void(0);" class="bshare-qzone" title="分享到QQ空间"></a>
                    </div>
                    <script type="text/javascript" charset="utf-8" src="http://static.bshare.cn/b/buttonLite.js#style=-1&amp;uuid=&amp;pophcol=2&amp;lang=zh"></script>
                    <script type="text/javascript" charset="utf-8" src="http://static.bshare.cn/b/bshareC0.js"></script>
                    <script type="text/javascript" charset="utf-8">
                        bShare.addEntry({
                            title: '{$article.title}',
                            url: 'http://weibo.com/208139345',
                            summary: '{$article.description}',
                            pic: 'http://ww3.sinaimg.cn/bmiddle/b5003f58jw1erolckzw37j20qo0f2wg7.jpg'
                        });
                    </script>
                    <!-- 分享代码结束 -->
                </dd>
            </dl>
            <div class="clear"></div>
        </div>
        <div class="article_con">
            {$article.content}
        </div>
        <div class="loop_nav">
            <div class="prev">
                {if $pre}
                上一篇：<a href="{'article'|buildUrl:$pre.id}" target="_blank">{$pre.title}</a>
                {else}
                上一篇：没有了
                {/if}
            </div>
            <div class="next">
                {if $next}
                下一篇：<a href="{'article'|buildUrl:$next.id}" target="_blank">{$next.title}</a>
                {else}
                下一篇：没有了
                {/if}
            </div>
            <div class="clear"></div>
        </div>
    </div>
    <div class="clear"></div>
</div>
{include file="library/footer.lbi"}
</body>
</html>
