<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="{$siteKeywords}" name="keywords">
    <meta content="{$siteDescription}" name="description">
    <title>{$owner}</title>
<!--    <link href="css/bootstrap.min.css" type="text/css" rel="stylesheet">-->
    <link href="css/style.css" type="text/css" rel="stylesheet">
    <script type="text/javascript">
        //var data_provinces = {$json_provinces};
        var data_cities = {$json_cities};
        var data_districts = {$json_districts};
    </script>
    <script src="js/jquery-1.11.1.min.js" type="text/javascript"></script>
    <script src="js/jquery.slide.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=qySui8MiIZKshBmwwQLmX1HU"></script>
</head>
<body>
{include file="library/header.lbi"}
{include file="library/slider.lbi"}
<div class="main">
    <div class="about_cabrielle">
        <div class="about_cabrielle_l">
            <img src="images/about-cabrielle.jpg" alt="关于佳百莉">
        </div>
        <div class="about_cabrielle_r">
            <h3>佳百莉<span class="small-paragraph">ABOUT US</span></h3>
            <p>这是关于佳百莉的故事。本公司正规授权的经销商必须严格按照公司规定的价格体系进行销售，凡是发现以低于公司规定价格出售产品、销售假货、串货任何一种情况的经销商，一经查实，将会立刻取消授权资格，并拉入黑名单。这是关于佳百莉的故事。本公司正规授权的经销商必须严格按照公司规定的价格体系进行销售，凡是发现以低于公司规定价格出售产品、销售假货、串货任何一种情况的经销商，一经查实，将会立刻取消授权资格，并拉入黑名单。</p>
        </div>
        <div class="clear"></div>
    </div>
    <div class="main_col">
        <div class="col_l">
            <h3><a target="_blank" href="articleCat.php?id=1"><img src="images/ico1.png" alt="品牌故事icon"></a></h3>
            {$first = true}
            {foreach from=$brandStory item=article}
                {if $first eq true}
                    <a class="a_dt" target="_blank" href="article.php?id={$article.id}"><img src="./{$article.img}" alt="{$article.title}"/><span>{$article.title}</span></a>
                    {$first = false}
                {else}
                    <dl class="col_dl">
                        <dt><a target="_blank" href="article.php?id={$article.id}"><img width="50px" height="50px" src="./{$article.img_shortcut}" alt="{$article.title}"/></a></dt>
                        <dd>
                            <b><a class="link_black" target="_blank" href="article.php?id={$article.id}">{$article.title}</a></b>
                            <p>作者：{$article.author}<i>{$article.publishTime}</i></p>
                        </dd>
                    </dl>
                {/if}
            {/foreach}
            <div class="readmore">
                <a target="_blank" href="articleCat.php?id=1">查看更多→</a>
            </div>
        </div>
        <div class="col_m">
            <h3><a target="_blank" href="articleCat.php?id=2"><img src="images/ico2.png" alt="企业新闻icon"></a></h3>
            {$first = true}
            {foreach from=$enterpriseNews item=article}
            {if $first eq true}
            <a class="a_dt" target="_blank" href="article.php?id={$article.id}"><img src="./{$article.img}" alt="{$article.title}"><span>{$article.title}</span></a>
            {$first = false}
            {else}
            <dl class="col_dl">
                <dt><a target="_blank" href="article.php?id={$article.id}"><img width="50px" height="50px" src="./{$article.img_shortcut}" alt="{$article.title}"></a></dt>
                <dd>
                    <b><a class="link_black" target="_blank" href="article.php?id={$article.id}">{$article.title}</a></b>
                    <p>作者：{$article.author}<i>{$article.publishTime}</i></p>
                </dd>
            </dl>
            {/if}
            {/foreach}
            <div class="readmore">
                <a target="_blank" href="articleCat.php?id=2">查看更多→</a>
            </div>
        </div>
        <div class="col_r">
            <h3><a target="_blank" href="articleCat.php?id=3"><img src="images/ico3.png" alt="美妆学院icon"></a></h3>
            {$first = true}
            {foreach from=$colleges item=article}
            {if $first eq true}
            <a class="a_dt" target="_blank" href="article.php?id={$article.id}"><img src="./{$article.img}" alt="{$article.title}"><span>{$article.title}</span></a>
            {$first = false}
            {else}
            <dl class="col_dl">
                <dt><a target="_blank" href="article.php?id={$article.id}"><img width="50px" height="50px" src="./{$article.img_shortcut}" alt="{$article.title}"></a></dt>
                <dd>
                    <b><a class="link_black" target="_blank" href="article.php?id={$article.id}">{$article.title}</a></b>
                    <p>作者：{$article.author}<i>{$article.publishTime}</i></p>
                </dd>
            </dl>
            {/if}
            {/foreach}
            <div class="readmore">
                <a target="_blank" href="articleCat.php?id=3">查看更多→</a>
            </div>
        </div>
    </div>
    <div class="clear"></div>
    <!--div class="banner">
        <img src="images/banner.jpg" alt="banner">
    </div-->
    {include file="library/ads.lbi"}
    {include file="library/map.lbi"}
    <div class="clear"></div>
</div>
{include file="library/footer.lbi"}
</body>
</html>
